### ISSUE TITLE
Some windows don't have a bundleID()

### ISSUE THREAD

**Issue by sje30** [evantravers/Split.spoon#1]
Hi,

thank you for Split.spoon.  I've got it working, although noticed a problem with some windows that I run.

For example, with the R application. (https://cran.r-project.org/bin/macosx/) if you run R within a terminal, and do something like

    plot(1:10)

you should get a new window, with a title like 'Quartz'.

I was getting an error on this line of m.split 

    image = hs.image.imageFromAppBundle(win:application():bundleID()),

so I've written the following as a workaround; so now the image is retrieved if possible, otherwise there is nothing

<img width="603" alt="Screenshot 2023-05-30 at 21 21 59" src="https://github.com/evantravers/Split.spoon/assets/1095067/f0aa7e47-26b5-411a-9212-27fefec01952">

here is the ,modified tex for m.split where bundle and possible image is computed before the return call.   Does this make sense?

```
m.split = function()
  local windows = hs.fnutils.map(hs.window.orderedWindows(), function(win)
    if win ~= hs.window.focusedWindow() then
       local bundle=win:application():bundleID()
       local image=nil
       if bundle then
	  image=hs.image.imageFromAppBundle(bundle)
       end
       return {
        text = win:title(),
        subText = win:application():title(),
	--sje comment next line
        --image = hs.image.imageFromAppBundle(win:application():bundleID()),
	image=image,
        id = win:id()
      }
    end
  end)
```

you can see that I had the same issue with outputs from the Julia program (gksqt program).

**Comment by sje30** [comment]
if you prefer a PR, I can make one.

**Comment by evantravers** [comment]
Thanks for the feedback @sje30. I understand the problem now.

Why don't you make a PR if you want… I probably would recommend extracting out the logic for the image detection into a function something along the lines of `m.image(Application)` that handles the if/then inside of it to keep split readable… but I can adjust whatever you request.

Great suggestion, thanks for encouraging me that someone actually uses this stuff. 🙏

**Comment by evantravers** [comment]
@sje30, there's a new version out that should fix your problem.

**Comment by sje30** [comment]
oh, wonderful, thank you!  I will try it out asap.
